#%RAML 1.0 NamedExample
<Shipments>
	<Shipment BatchNumber="27414866" ForwardingEntityId="com.taneira" ForwardingEntityPassword="C0mTaN31rA" MerchantName="Taneira-Online" OrderNo="9545913" OrganizationName="Taneira" POSEntryMode="2" POSTypeId="1" Password="T@n3I7A0N1iN9" TerminalId="Taneira-OL-01" TransactionDate="2023-10-05T08:47:56" TransactionId="21104" UserName="taneiraol.inituser">
		<ShipmentLines>
			<ShipmentLine>
				<OrderLine>
					<PersonInfoShipTo FirstName="Suja" LastName="Nambiar" MobilePhone="9620824287"/>
					<Extn>
						<TitanGCLineDetailList>
							<TitanGCLineDetail Amount="5000.00" GiftCardNo="1004050010092239"/>
						</TitanGCLineDetailList>
					</Extn>
				</OrderLine>
			</ShipmentLine>
		</ShipmentLines>
	</Shipment>
</Shipments>