#%RAML 1.0 NamedExample
<Order CardProgGrpName="Tanishq Retail Online eGift Card" OrderNo="SFTQ000028140">
	<OrderLines>
		<OrderLine ForwardingEntityId="com.tanishq" ForwardingEntityPassword="C0m@T@n15Hq" OrderLineKey="202309161820185247434054" Password="7@n1S6Q0lIn1TU53R" TerminalId="POS-Tanishq-Online-01" UserName="tanishqol.inituser">
			<LinePriceInfo UnitPrice="10000.00"/>
		</OrderLine>
	</OrderLines>
	<PersonInfoShipTo AddressLine1="Plot no 63" AddressLine2="Plot no 63 NCL colony beside Delhi International school kompally 500100" EMailID="allenkyvamshi@gmail.com" FirstName="Vamshi krishna" LastName="Allenky" MobilePhone="7674067890" ZipCode="500100"/>
	<PersonInfoBillTo EMailID="allenkyvamshi@gmail.com" FirstName="Vamshi krishna" LastName="Allenky" MobilePhone="7674067890"/>
	<TitanGCLineDetail BatchNumber="27183326" MerchantName="Tanishq-Online" OrganizationName="Tanishq" POSEntryMode="2" POSTypeId="1" TransactionDate="2023-09-18T00:00:10" TransactionId="20996"/>
</Order>