#%RAML 1.0 NamedExample
<XMLNSC>
	<TitanGCLineDetail MerchantName="Tanishq-Online" TransactionDate="2023-09-18T00:00:10" POSTypeId="1" POSEntryMode="2" CardNumber="1005260024340000" CardExpiry="2024-09-17T00:00:11.033" BatchNumber="27183326" ResponseCode="0" ResponseMessage="Transaction successful." TransactionId="20996" CardPIN="282691" InvoiceNumber="202309161820185247434054"/>
</XMLNSC>