#%RAML 1.0 NamedExample
<Payment Amount="3000.0" CardNumber="1000270110884721" CardPIN="143816" CurrentBatchNumber="27422720" DateAtClient="2023-10-05T21:23:51" ForwardingEntityId="com.tclecom" ForwardingEntityPassword="c0m.t(13C0M" MerchantOutletName="Titan.co.in" OrganizationName="Titan Company Ecom" OriginalBatchNo="27417582" OriginalTransactionId="9742" POSEntryMode="2" POSTypeId="1" Password="user@w3bp0s4tC13C0M" TerminalId="TCLECOM:TCLECOM-WEBPOS-WEB-09" TransactionId="21106" UserName="tclecomwebuser"/>