#%RAML 1.0 NamedExample
<XMLNSC>
	<Payment CardNumber="1000270110884721" CardExpiry="2024-02-28T00:00:00" Amount="3000" RefundTransactionReference="3539258381" Status="0" ResponseMessage="Transaction successful." TransactionId="21106" TransactionType="12"/>
</XMLNSC>